version: '3.8'

services:
  # Tu servicio de Base de Datos
  ecommerce-mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    environment:
      # ... tus variables de entorno existentes ...
      MYSQL_ROOT_PASSWORD: root  # Ejemplo
      MYSQL_DATABASE: db_ecommerce_jwt
    # AGREGA ESTO: ----------------------------------
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    # -----------------------------------------------

  ecommerce-jwt-app:
    build: .
    container_name: ecommerce-app
    ports:
      - "8080:8080"
    environment:
      # Aseg√∫rate que la URL de la DB coincida con el nombre del servicio (ecommerce-mysql)
      SPRING_DATASOURCE_URL: "jdbc:mysql://ecommerce-mysql:3306/db_ecommerce_jwt?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
    # AGREGA ESTO: ----------------------------------
    depends_on:
      ecommerce-mysql:
        condition: service_healthy
    restart: on-failure
    # -----------------------------------------------